# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\조재용\PycharmProjects\BRPI\BRPI_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.Background.setStyleSheet("background-image: url(:/Background/Bithumb Realtime Price Information.png);")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.label_BTC = QtWidgets.QLabel(self.centralwidget)
        self.label_BTC.setGeometry(QtCore.QRect(210, 170, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_BTC.setFont(font)
        self.label_BTC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_BTC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_BTC.setObjectName("label_BTC")
        self.label_ETH = QtWidgets.QLabel(self.centralwidget)
        self.label_ETH.setGeometry(QtCore.QRect(210, 225, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_ETH.setFont(font)
        self.label_ETH.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ETH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ETH.setObjectName("label_ETH")
        self.label_XRP = QtWidgets.QLabel(self.centralwidget)
        self.label_XRP.setGeometry(QtCore.QRect(210, 280, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_XRP.setFont(font)
        self.label_XRP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_XRP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XRP.setObjectName("label_XRP")
        self.label_BCH = QtWidgets.QLabel(self.centralwidget)
        self.label_BCH.setGeometry(QtCore.QRect(210, 335, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_BCH.setFont(font)
        self.label_BCH.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_BCH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_BCH.setObjectName("label_BCH")
        self.label_EOS = QtWidgets.QLabel(self.centralwidget)
        self.label_EOS.setGeometry(QtCore.QRect(210, 390, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_EOS.setFont(font)
        self.label_EOS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_EOS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EOS.setObjectName("label_EOS")
        self.label_XMR = QtWidgets.QLabel(self.centralwidget)
        self.label_XMR.setGeometry(QtCore.QRect(480, 280, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_XMR.setFont(font)
        self.label_XMR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_XMR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_XMR.setObjectName("label_XMR")
        self.label_ADA = QtWidgets.QLabel(self.centralwidget)
        self.label_ADA.setGeometry(QtCore.QRect(480, 225, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_ADA.setFont(font)
        self.label_ADA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ADA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ADA.setObjectName("label_ADA")
        self.label_TRX = QtWidgets.QLabel(self.centralwidget)
        self.label_TRX.setGeometry(QtCore.QRect(480, 335, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_TRX.setFont(font)
        self.label_TRX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TRX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_TRX.setObjectName("label_TRX")
        self.label_DASH = QtWidgets.QLabel(self.centralwidget)
        self.label_DASH.setGeometry(QtCore.QRect(480, 390, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_DASH.setFont(font)
        self.label_DASH.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_DASH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_DASH.setObjectName("label_DASH")
        self.label_LTC = QtWidgets.QLabel(self.centralwidget)
        self.label_LTC.setGeometry(QtCore.QRect(480, 170, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_LTC.setFont(font)
        self.label_LTC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_LTC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_LTC.setObjectName("label_LTC")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_BTC.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_ETH.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_XRP.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_BCH.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_EOS.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_XMR.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_ADA.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_TRX.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_DASH.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))
        self.label_LTC.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#4c4c4c;\">0</span></p></body></html>"))

import Background

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

